functionsDirectory = "/home/ben/Workspace/on-pitch/netlify/functions"
functionsDirectoryOrigin = "config-v1"
redirectsOrigin = "config"
plugins = []
headers = []

[functions]

[functions."*"]

[build]
publish = "/home/ben/Workspace/on-pitch/build/client"
publishOrigin = "config"
commandOrigin = "config"
command = "pnpm run build"
functions = "/home/ben/Workspace/on-pitch/netlify/functions"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[[redirects]]
from = "/*"
to = "/index.html"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]