[[workflows]]
name = "prepare-release"

[[workflows.steps]]
command = "git switch -c release"
type = "Command"

[[workflows.steps]]
ignore_conventional_commits = true
type = "PrepareRelease"

[[workflows]]
name = "create-pr"

[[workflows.steps]]
base = "main"
type = "CreatePullRequest"

[workflows.steps.title]
template = "chore: prepare release"

[workflows.steps.body]
template = "This PR was created by Knope. Merging it will create a new release"

[[workflows]]
name = "document-change"

[[workflows.steps]]
type = "CreateChangeFile"

[[workflows]]
name = "release"

[[workflows.steps]]
type = "Release"

[github]
owner = "doc-E-brown"
repo = "on-pitch"
