name: prepare-release.yml
on:
  push:
    branches: [ main ]

jobs:
  prepare-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2
        name: Fetch entire history (for conventional commits)
        with:
          fetch-depth: 0
          token: ${{ secrets.PAT }}
      - name: Configure Git
        run: |
          git config --global user.name GitHub Actions
          git config user.email github-actions@github.com
      - name: Install Knope
        uses: knope-dev/action@v2.1.0
        with:
          version: 0.20.0
      - run: knope prepare-release --verbose
        name: Update versioned files and changelog
      - name: Update branch
        run: |
          git add .
          SKIP=end-of-file-fixer git commit -m "chore: prepare release"
          git push --force --set-upstream origin release
      - run: knope create-pr --verbose
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}




